# Generated by Django 3.0.5 on 2020-04-12 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductId',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный ID изделия')),
                ('img', models.ImageField(upload_to='img/')),
                ('template', models.CharField(choices=[('1527', '1527'), ('2032', '2032'), ('2104', '2104'), ('4021', '4021'), ('4030', '4030')], max_length=4)),
                ('payment_id', models.CharField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
