# Generated by Django 3.0.5 on 2020-06-13 09:45

from django.db import migrations, models
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0002_auto_20200412_1351_squashed_0012_auto_20200512_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Инструкция')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('town', models.CharField(max_length=30, verbose_name='Город')),
                ('ed_institution', models.CharField(max_length=50, verbose_name='Номер школы/детского сада')),
                ('the_class', models.CharField(max_length=20, verbose_name='класс/группа')),
                ('foto_from_client', models.ImageField(upload_to=manage_product.models.FotoOrder.upload_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
