# Generated by Django 3.0.5 on 2020-04-18 15:40

from django.db import migrations, models
import django.db.models.deletion
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0003_auto_20200415_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Электронные почты', 'verbose_name_plural': 'электронная почта'},
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default='email@email.ru', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='date_close',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки заказа'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_product.Email', verbose_name='e-mail клиента'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='img',
            field=models.ImageField(upload_to=manage_product.models.ProductId.upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='stage',
            field=models.CharField(choices=[('new', 'Новый'), ('pay', 'Оплата'), ('in_work', 'Верстка'), ('perfomed', 'Выполнено')], default=1, max_length=10, verbose_name='Статус'),
        ),
    ]
