# Generated by Django 3.0.5 on 2020-05-08 16:02

from django.db import migrations, models
import django.db.models.deletion
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_productid_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='productid',
            name='img_jpg',
            field=models.ImageField(null=True, upload_to=manage_product.models.ProductId.upload_path, verbose_name='Фото для скачивания'),
        ),
        migrations.AddField(
            model_name='productid',
            name='organisation',
            field=models.CharField(choices=[('Школа', 'school'), ('Детский сад', 'playschool')], default=1, max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='img',
            field=models.ImageField(null=True, upload_to=manage_product.models.ProductId.upload_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='productid',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_product.Town', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='productid',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_product.Worker', verbose_name='Менеджер'),
        ),
    ]
