# Generated by Django 3.0.5 on 2020-05-09 15:47

from django.db import migrations, models
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0007_auto_20200508_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='productid',
            name='organisation_name',
            field=models.CharField(default='1', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='organisation',
            field=models.CharField(choices=[('school', 'Школа'), ('playschool', 'Детский сад')], default=1, max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='payment_id',
            field=models.CharField(default=manage_product.models.ProductId.generate_pay_id, max_length=10, verbose_name='id оплаты'),
        ),
    ]
