# Generated by Django 3.0.5 on 2020-05-09 16:27

from django.db import migrations, models
import django.db.models.deletion
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0009_auto_20200509_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productid',
            name='img_jpg',
            field=models.ImageField(blank=True, null=True, upload_to=manage_product.models.ProductId.upload_path, verbose_name='Фото для скачивания'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='organisation_name',
            field=models.CharField(blank=True, default='1', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='payment_id',
            field=models.CharField(default=manage_product.models.ProductId.generate_pay_id, max_length=10, verbose_name='id оплаты'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_product.Town', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_product.Worker', verbose_name='Менеджер'),
        ),
    ]
