# Generated by Django 3.0.5 on 2020-05-09 16:28

from django.db import migrations, models
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0010_auto_20200509_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productid',
            name='payment_id',
            field=models.CharField(default=manage_product.models.ProductId.generate_pay_id, max_length=10, unique=True, verbose_name='id оплаты'),
        ),
    ]
