# Generated by Django 3.0.5 on 2020-05-12 12:42

from django.db import migrations, models
import manage_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0011_auto_20200509_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productid',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=manage_product.models.ProductId.upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productid',
            name='product_link',
            field=models.CharField(blank=True, default='link', max_length=100, verbose_name='Ссылка на изделие'),
        ),
    ]
