# Generated by Django 3.1.6 on 2021-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1, verbose_name='Положение в меню')),
                ('section_name', models.CharField(max_length=50, verbose_name='Раздел')),
                ('section_url', models.CharField(max_length=100, verbose_name='Ссылка на раздел')),
            ],
            options={
                'verbose_name': 'Меню сайта',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
