# Generated by Django 3.0.5 on 2020-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=15, verbose_name='Раздел')),
                ('section_url', models.URLField(verbose_name='Ссылка на раздел')),
            ],
            options={
                'verbose_name': 'Меню сайта',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
