# Generated by Django 3.0.5 on 2020-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='section_number',
            field=models.IntegerField(default=1, verbose_name='Положение в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section_name',
            field=models.CharField(max_length=50, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section_url',
            field=models.CharField(max_length=100, verbose_name='Ссылка на раздел'),
        ),
    ]
